### ISSUE TITLE
O que essa div tá fazendo ai? Sem conteúdo?

### ISSUE THREAD

**Issue by baltazarparra** [pachicodes/SessON-website#1]
https://github.com/pachicodes/SessON-website/blob/aa26f995f1d9c8bd8788c57158c9d2df7456ee0d/index.html#L15

**Comment by pachicodes** [comment]
essa div nao ta vazia de verdade. Ele que da a caidinha pro backgoung sem da a caidinha pra letras.

**Comment by baltazarparra** [comment]
Tá demitida

**Comment by pachicodes** [comment]
fora da banda
