### ISSUE TITLE
Esse estilo aqui se repete em 3 lugares, dá pra pensar em uma classe só pra resolver eles.

### ISSUE THREAD

**Issue by baltazarparra** [pachicodes/SessON-website#5]
https://github.com/pachicodes/SessON-website/blob/aa26f995f1d9c8bd8788c57158c9d2df7456ee0d/index.html#L37

**Comment by pachicodes** [comment]
pdp

**Comment by pachicodes** [comment]
vai lah arrumar vc HHAHAHA eu te assignei, que boss eu
