### ISSUE TITLE
Não use comentários, as classes precisam ser descritivas o suficiente pra você não precisar disso

### ISSUE THREAD

**Issue by baltazarparra** [pachicodes/SessON-website#8]
https://github.com/pachicodes/SessON-website/blob/aa26f995f1d9c8bd8788c57158c9d2df7456ee0d/css/main.css#L7

**Comment by pachicodes** [comment]
mas mas mas masss!!!!! 
todo mundo das aulas fez isso?

**Comment by baltazarparra** [comment]
você não é todo mundo das aula
